site_name: 'Learn about the Blue0x Network'
site_description: 'Learn about the Blue0x Network'
site_author: 'Blue0x Devs'
docs_dir: docs/
nav:
  - Home: 
    - Home: index.md
    - Learn More: learn_more/index.md
    - API: api/index.md
    - Setup: setup/index.md
    - Node Rewards: node_rewards/index.md

  - Learn More:
    - What is Blue0x?: learn_more/index.md

  - API:
    - ALL: api/index.md
    - OVERVIEW: api/overview.md
    - TABLE OF CONTENTS: api/toc.md
    - Account: api/account.md
    - Alias: api/alias.md
    - Assets: api/assets.md
    - Blocks: api/blocks.md
    - Debug: api/debug.md
    - Forging: api/forging.md
    - Hallmark: api/hallmark.md
    - Marketplace: api/marketplace.md
    - Messaging: api/messaging.md
    - Monetary System: api/monetary_system.md
    - Networking: api/networking.md
    - Phasing: api/phasing.md
    - Server: api/server.md
    - Shuffling: api/shuffling.md
    - Tagged Data: api/tagged_data.md
    - Token: api/token.md
    - Transactions: api/transactions.md
    - Utilities: api/utilities.md
    - Voting: api/voting.md
    - API Examples: api/API_Examples.md

  - Setup:
    - Setup: setup/index.md

  - Node Rewards:
    - How-To: node_rewards/index.md

theme:
    name: material
    custom_dir: material/overrides/
    logo: img/logo.png
    favicon: img/favicon.ico
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
    features:
    - navigation.tabs
    - navigation.instant
    - header.autohide




