site_name: 'Learn about the Blue0x Network'
site_description: 'Learn about the Blue0x Network'
site_author: 'Blue0x Devs'
docs_dir: docs/
nav:
  - Home: 
    - Home: index.md
    - Learn More: learn_more/what.md
    - API: all.md

  - Learn More:
    - What is Blue0x?: learn_more/what.md
    - Why should I care?: learn_more/why.md

  - API:
    - ALL: all.md
    - OVERVIEW: general.md
    - TABLE OF CONTENTS: toc.md
    - Account: account.md
    - Alias: alias.md
    - Assets: assets.md
    - Blocks: blocks.md
    - Debug: debug.md
    - Forging: forging.md
    - Hallmark: hallmark.md
    - Marketplace: marketplace.md
    - Messaging: messaging.md
    - Monetary System: monetary_system.md
    - Networking: networking.md
    - Phasing: phasing.md
    - Server: server.md
    - Shuffling: shuffling.md
    - Tagged Data: tagged_data.md
    - Token: token.md
    - Transactions: transactions.md
    - Utilities: utilities.md
    - Voting: voting.md
    - API Examples: API_Examples.md

theme:
    name: material
    custom_dir: material/overrides/
    logo: img/logo.png
    favicon: img/favicon.ico
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
    features:
    - navigation.tabs
    - navigation.instant
    - header.autohide




