site_name: Blue0x API Docs
site_description: 'Blue0x API Documentation'
site_author: 'Blue0x Devs'
docs_dir: docs/
nav:
    - ALL: index.md
    - OVERVIEW: general.md
    - TABLE OF CONTENTS: toc.md
    - Account: account.md
    - Alias: alias.md
    - Assets: assets.md
    - Blocks: blocks.md
    - Debug: debug.md
    - Forging: forging.md
    - Hallmark: hallmark.md
    - Marketplace: marketplace.md
    - Messaging: messaging.md
    - Monetary System: monetary_system.md
    - Networking: networking.md
    - Phasing: phasing.md
    - Server: server.md
    - Shuffling: shuffling.md
    - Tagged Data: tagged_data.md
    - Token: token.md
    - Transactions: transactions.md
    - Utilities: utilities.md
    - Voting: voting.md
    - API Examples: API_Examples.md
theme:
    name: material
    icon:
        logo: 'material/server-network'
    favicon: img/favicon.ico
    palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: blue





